# Generated by Django 6.0.2 on 2026-02-07 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cancelled_at_booking_cancelled_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='carrier_booking_ref',
            field=models.CharField(blank=True, help_text='Carrier-assigned booking reference', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='commodity_description',
            field=models.CharField(blank=True, help_text='General description of goods being shipped', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Customer or external system reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='incoterms',
            field=models.CharField(choices=[('FOB', 'FOB - Free on Board'), ('CFR', 'CFR - Cost and Freight'), ('CIF', 'CIF - Cost, Insurance and Freight'), ('EXW', 'EXW - Ex Works'), ('FCA', 'FCA - Free Carrier'), ('CPT', 'CPT - Carriage Paid To'), ('CIP', 'CIP - Carriage and Insurance Paid To'), ('DAP', 'DAP - Delivered at Place'), ('DPU', 'DPU - Delivered at Place Unloaded'), ('DDP', 'DDP - Delivered Duty Paid'), ('FAS', 'FAS - Free Alongside Ship')], default='FOB', help_text='INCOTERMS 2020 trade terms', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='incoterms_location',
            field=models.CharField(blank=True, help_text='Named place for the selected INCOTERM (e.g. port or warehouse)', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_hazardous',
            field=models.BooleanField(default=False, help_text='Does this booking contain any hazardous materials?'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='source_channel',
            field=models.CharField(choices=[('WEB', 'Web Portal'), ('API', 'API'), ('EDI', 'EDI'), ('CSV', 'CSV/XLSX Import'), ('MANUAL', 'Manual Entry')], default='WEB', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_volume_cbm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total cargo volume in cubic meters (auto-calculated from items)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cargo weight in kg (auto-calculated from items)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System code (6-10 digits)', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='imo_class',
            field=models.CharField(blank=True, help_text='IMO hazard class (e.g. 3, 6.1, 8)', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='is_hazardous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in centimeters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='marks_and_numbers',
            field=models.CharField(blank=True, help_text='Shipping marks and package numbers', max_length=500),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='un_number',
            field=models.CharField(blank=True, help_text='UN number for hazardous goods (e.g. 1234)', max_length=4),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='volume_cbm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volume in cubic meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in centimeters', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('OPERATIONS', 'Operations'), ('SALES', 'Sales')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_TRANSIT', 'Marked In Transit'), ('COMPLETED', 'Completed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('PARTY_ADDED', 'Party Added'), ('PARTY_REMOVED', 'Party Removed'), ('ITEM_ADDED', 'Cargo Item Added'), ('ITEM_UPDATED', 'Cargo Item Updated'), ('ITEM_REMOVED', 'Cargo Item Removed')], max_length=30)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_value', models.JSONField(blank=True, help_text='Previous state (JSON)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state (JSON)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.booking')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SHIPPER', 'Shipper'), ('CONSIGNEE', 'Consignee'), ('NOTIFY', 'Notify Party'), ('BROKER', 'Customs Broker'), ('FREIGHT_FORWARDER', 'Freight Forwarder'), ('OTHER', 'Other')], max_length=30)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g. US, CN, DE)', max_length=2)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID / VAT number', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Default party for this role under this customer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='The customer account that owns this party record', on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='bookings.customer')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='BookingParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SHIPPER', 'Shipper'), ('CONSIGNEE', 'Consignee'), ('NOTIFY', 'Notify Party'), ('BROKER', 'Customs Broker'), ('FREIGHT_FORWARDER', 'Freight Forwarder'), ('OTHER', 'Other')], max_length=30)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('address_text', models.TextField(blank=True, help_text='Full address as a single text block (snapshot)')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_parties', to='bookings.booking')),
                ('party', models.ForeignKey(blank=True, help_text='Link to the address book entry (null if party was deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_assignments', to='bookings.party')),
            ],
            options={
                'verbose_name_plural': 'booking parties',
                'ordering': ['role', 'company_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer', 'role'), name='unique_default_party_per_role'),
        ),
        migrations.AddConstraint(
            model_name='bookingparty',
            constraint=models.UniqueConstraint(fields=('booking', 'role'), name='unique_party_role_per_booking'),
        ),
    ]
