# Generated by Django 6.0.2 on 2026-02-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_phase1_5_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cargo_cutoff_date',
            field=models.DateField(blank=True, help_text='Deadline for cargo to arrive at port/terminal (set by operations)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_mode',
            field=models.CharField(choices=[('SEA_FCL', 'Sea - FCL'), ('SEA_LCL', 'Sea - LCL'), ('AIR', 'Air Freight'), ('RAIL', 'Rail'), ('TRUCK', 'Trucking'), ('MULTIMODAL', 'Multimodal')], default='SEA_FCL', help_text='Mode of transport for this shipment', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingdocument',
            name='document_type',
            field=models.CharField(choices=[('COMMERCIAL_INVOICE', 'Commercial Invoice'), ('PACKING_LIST', 'Packing List'), ('BILL_OF_LADING', 'Bill of Lading'), ('AIRWAY_BILL', 'Airway Bill'), ('CUSTOMS_DECLARATION', 'Customs Declaration'), ('CERTIFICATE_OF_ORIGIN', 'Certificate of Origin'), ('SHIPPING_ADVICE', 'Shipping Advice'), ('CARGO_MANIFEST', 'Cargo Manifest'), ('LOADING_PLAN', 'Loading Plan'), ('INSURANCE_CERTIFICATE', 'Insurance Certificate'), ('FUMIGATION_CERT', 'Fumigation Certificate'), ('INSPECTION_REPORT', 'Inspection Report'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
