# Generated by Django 6.0.2 on 2026-02-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_phase25_transport_mode_cutoff_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Internal carrier contract number (not visible to customers)', max_length=100),
        ),
    ]
