# Generated by Django 6.0.2 on 2026-02-09 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_contract_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_arrival_date',
            field=models.DateField(blank=True, help_text='Actual date cargo arrived at destination (set when completing)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_departure_date',
            field=models.DateField(blank=True, help_text='Actual date vessel/flight departed (set when marking in transit)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_TRANSIT', 'Marked In Transit'), ('COMPLETED', 'Completed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('PARTY_ADDED', 'Party Added'), ('PARTY_REMOVED', 'Party Removed'), ('ITEM_ADDED', 'Cargo Item Added'), ('ITEM_UPDATED', 'Cargo Item Updated'), ('ITEM_REMOVED', 'Cargo Item Removed'), ('RESUBMITTED', 'Resubmitted from Rejection')], max_length=30),
        ),
    ]
