# Generated by Django 6.0.2 on 2026-02-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_ba_review_milestones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingitem',
            options={'ordering': ['id'], 'verbose_name': 'cargo line item', 'verbose_name_plural': 'cargo line items'},
        ),
    ]
