# Generated by Django 6.0.2 on 2026-02-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_bookingitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Accent/button color hex, e.g. #DC3545', max_length=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (recommended: 200x50px PNG with transparent bg)', null=True, upload_to='customer_logos/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='portal_name',
            field=models.CharField(blank=True, default='', help_text='Custom portal name shown in navbar', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Primary brand color hex, e.g. #1E2A4A', max_length=7),
        ),
    ]
