# Generated by Django 6.0.2 on 2026-02-09 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_customer_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Accent/button color hex, e.g. #DC3545', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code (e.g. #1E2A4A).')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (recommended: 200x50px PNG with transparent bg)', null=True, upload_to='customer_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Primary brand color hex, e.g. #1E2A4A', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code (e.g. #1E2A4A).')]),
        ),
    ]
