# Generated by Django 6.0.2 on 2026-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_customer_branding_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fms_push_error',
            field=models.TextField(blank=True, help_text='Last FMS push error message'),
        ),
        migrations.AddField(
            model_name='booking',
            name='fms_push_status',
            field=models.CharField(blank=True, choices=[('', 'Not Configured'), ('PENDING', 'Pending'), ('PUSHED', 'Pushed'), ('FAILED', 'Failed'), ('CALLBACK_RECEIVED', 'Callback Received')], default='', help_text='Status of FMS integration push', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='fms_shipment_id',
            field=models.CharField(blank=True, help_text='Shipment ID in external FMS', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='hawb_number',
            field=models.CharField(blank=True, help_text='House Airway Bill number', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='hbl_number',
            field=models.CharField(blank=True, help_text='House Bill of Lading number', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='mawb_number',
            field=models.CharField(blank=True, help_text='Master Airway Bill number', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='mbl_number',
            field=models.CharField(blank=True, help_text='Master Bill of Lading number', max_length=50),
        ),
    ]
