# Generated by Django 6.0.2 on 2026-02-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_fms_integration_fields'),
        ('integrations', '0002_carrier_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='carrier_config',
            field=models.ForeignKey(blank=True, help_text='Carrier API config used for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='integrations.carrierconfig'),
        ),
        migrations.AddField(
            model_name='booking',
            name='carrier_confirmation_ref',
            field=models.CharField(blank=True, help_text='Carrier-side confirmation reference from their API', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='carrier_request_error',
            field=models.TextField(blank=True, help_text='Last carrier API error message'),
        ),
        migrations.AddField(
            model_name='booking',
            name='carrier_request_status',
            field=models.CharField(blank=True, choices=[('', 'Not Submitted'), ('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to Carrier'), ('CONFIRMED', 'Carrier Confirmed'), ('REJECTED', 'Carrier Rejected'), ('FAILED', 'Submission Failed'), ('CANCELLED', 'Cancelled with Carrier')], default='', help_text='Status of carrier API booking request', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='container_numbers',
            field=models.TextField(blank=True, help_text='Carrier-assigned container numbers (one per line)'),
        ),
    ]
