# Generated by Django 6.0.2 on 2026-02-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_carrier_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chargeable_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chargeable weight in kg (max of actual vs volumetric weight)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(blank=True, help_text='Flight number for air freight (e.g. CX890)', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='container_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of containers (required for FCL shipments)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='container_type',
            field=models.ForeignKey(blank=True, help_text='Container type (required for FCL shipments)', null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.containertype'),
        ),
    ]
