# Generated by Django 6.0.2 on 2026-02-12 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_chargeable_weight_kg_booking_flight_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scac_code', models.CharField(help_text='SCAC code for ocean, IATA code for air', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('carrier_type', models.CharField(choices=[('OCEAN', 'Ocean Carrier'), ('AIR', 'Air Carrier'), ('RAIL', 'Rail Carrier'), ('TRUCKING', 'Trucking Carrier')], default='OCEAN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['country', 'name']},
        ),
        migrations.AddField(
            model_name='port',
            name='region',
            field=models.CharField(choices=[('EAST_ASIA', 'East Asia'), ('SOUTHEAST_ASIA', 'Southeast Asia'), ('SOUTH_ASIA', 'South Asia'), ('MIDDLE_EAST', 'Middle East'), ('EUROPE', 'Europe'), ('NORTH_AMERICA', 'North America'), ('SOUTH_AMERICA', 'South America'), ('AFRICA', 'Africa'), ('OCEANIA', 'Oceania')], default='NORTH_AMERICA', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
