# Generated by Django 6.0.2 on 2026-02-15 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_carrier_alter_port_options_port_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('notification_type', models.CharField(choices=[('BOOKING_SUBMITTED', 'Booking Submitted'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_IN_TRANSIT', 'Booking In Transit'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_RESUBMITTED', 'Booking Resubmitted'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='bookings_no_user_id_f81614_idx')],
            },
        ),
    ]
