# Generated by Django 6.0.2 on 2026-02-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_bookingtemplate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_default_party_per_role',
        ),
    ]
