# Generated by Django 6.0.2 on 2026-02-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_mysql_compat_remove_partial_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_TRANSIT', 'Marked In Transit'), ('ARRIVED', 'Arrived at Destination'), ('COMPLETED', 'Completed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('PARTY_ADDED', 'Party Added'), ('PARTY_REMOVED', 'Party Removed'), ('ITEM_ADDED', 'Cargo Item Added'), ('ITEM_UPDATED', 'Cargo Item Updated'), ('ITEM_REMOVED', 'Cargo Item Removed'), ('RESUBMITTED', 'Resubmitted from Rejection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_SUBMITTED', 'Booking Submitted'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_IN_TRANSIT', 'Booking In Transit'), ('BOOKING_ARRIVED', 'Booking Arrived'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_RESUBMITTED', 'Booking Resubmitted'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
        migrations.CreateModel(
            name='ShipmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('CARGO_RECEIVED', 'Cargo Received at Origin'), ('GATE_IN', 'Gate In at Terminal'), ('CUSTOMS_EXPORT', 'Export Customs Cleared'), ('LOADED', 'Loaded on Vessel/Flight'), ('DEPARTED', 'Departed Origin'), ('TRANSSHIPMENT', 'Transshipment'), ('ARRIVED_PORT', 'Arrived at Destination Port'), ('DISCHARGED', 'Discharged from Vessel'), ('CUSTOMS_IMPORT', 'Import Customs Cleared'), ('GATE_OUT', 'Gate Out from Terminal'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered to Consignee'), ('OTHER', 'Other')], max_length=30)),
                ('occurred_at', models.DateTimeField(help_text='When this milestone actually occurred')),
                ('location', models.CharField(blank=True, help_text='Location/port where this occurred', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bookings.booking')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shipment milestone',
                'ordering': ['occurred_at'],
            },
        ),
    ]
