# Generated by Django 6.0.2 on 2026-02-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_arrived_status_and_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone name, e.g. Asia/Singapore. Blank = UTC.', max_length=50),
        ),
    ]
