# Generated by Django 6.0.2 on 2026-02-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_status_packing_customer_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lcl_consolidation_number',
            field=models.CharField(blank=True, help_text='Consolidation number for LCL shipments (assigned by forwarder)', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_TRANSIT', 'Marked In Transit'), ('ARRIVED', 'Arrived at Destination'), ('COMPLETED', 'Completed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('PARTY_ADDED', 'Party Added'), ('PARTY_REMOVED', 'Party Removed'), ('ITEM_ADDED', 'Cargo Item Added'), ('ITEM_UPDATED', 'Cargo Item Updated'), ('ITEM_REMOVED', 'Cargo Item Removed'), ('RESUBMITTED', 'Resubmitted from Rejection'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('RECONFIRMED', 'Re-confirmed after Customer Rejection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='external_reference',
            field=models.CharField(help_text='Customer or external system reference number (required)', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_SUBMITTED', 'Booking Submitted'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_IN_TRANSIT', 'Booking In Transit'), ('BOOKING_ARRIVED', 'Booking Arrived'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_RESUBMITTED', 'Booking Resubmitted'), ('BOOKING_CUSTOMER_APPROVED', 'Booking Customer Approved'), ('BOOKING_CUSTOMER_REJECTED', 'Booking Customer Rejected'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
    ]
