# Generated by Django 6.0.2 on 2026-02-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_add_lcl_consolidation_require_external_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('AWS', 'AWS - All Water Service'), ('IPI', 'IPI - Interior Point Intermodal'), ('MLB', 'MLB - Mini Land Bridge'), ('RIPI', 'RIPI - Reverse IPI'), ('CY_CY', 'CY-CY - Port to Port'), ('CY_SD', 'CY-SD - Port to Door'), ('SD_SD', 'SD-SD - Door to Door')], default='', help_text='Routing/service type (optional, e.g. AWS, IPI, MLB)', max_length=10),
        ),
        migrations.AddField(
            model_name='port',
            name='port_type',
            field=models.CharField(choices=[('SEA', 'Sea Port'), ('AIR', 'Airport'), ('BOTH', 'Sea & Air (Dual-use)')], default='SEA', max_length=4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transport_mode',
            field=models.CharField(choices=[('SEA_FCL', 'Sea - FCL'), ('SEA_LCL', 'Sea - LCL'), ('AIR', 'Air Freight'), ('SEA_AIR', 'Sea-Air'), ('AIR_SEA', 'Air-Sea'), ('RAIL', 'Rail'), ('TRUCK', 'Trucking'), ('MULTIMODAL', 'Multimodal')], default='SEA_FCL', help_text='Mode of transport for this shipment', max_length=20),
        ),
    ]
