# Generated by Django 6.0.2 on 2026-02-18 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_booking_service_type_port_port_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.UUIDField(help_text='Matches session import_id', unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('ANALYZING', 'Analyzing File'), ('PREVIEWING', 'Awaiting Confirmation'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ANALYZING', max_length=20)),
                ('extracted_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('extraction_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True, help_text='Error if entire import failed')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='bookings.customer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'import log',
                'verbose_name_plural': 'import logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='Zero-based index in extraction results')),
                ('row_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Valid with Warnings'), ('ERROR', 'Validation Error'), ('CREATED', 'Booking Created'), ('SKIPPED', 'Not Selected'), ('CREATE_FAILED', 'Creation Failed')], default='VALID', max_length=20)),
                ('confidence', models.CharField(blank=True, default='medium', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('was_selected', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_booking_logs', to='bookings.booking')),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_logs', to='bookings.importlog')),
            ],
            options={
                'verbose_name': 'import booking log',
                'verbose_name_plural': 'import booking logs',
                'ordering': ['import_log', 'row_index'],
            },
        ),
    ]
