# Generated by Django 6.0.2 on 2026-02-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_importlog_importbookinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source_channel',
            field=models.CharField(choices=[('WEB', 'Web Portal'), ('API', 'API'), ('EDI', 'EDI'), ('CSV', 'File Import'), ('MANUAL', 'Manual Entry')], default='WEB', max_length=10),
        ),
    ]
