# Generated by Django 6.0.2 on 2026-02-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_alter_booking_source_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='capacity_cbm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Internal cargo capacity in cubic meters', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='containertype',
            name='max_payload_kg',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Maximum payload weight in kilograms', max_digits=8, null=True),
        ),
    ]
