# Generated by Django 6.0.2 on 2026-02-18 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_service_type_to_move_type(apps, schema_editor):
    """Move CY_CY, CY_SD, SD_SD from service_type to move_type."""
    Booking = apps.get_model('bookings', 'Booking')
    move_type_values = {'CY_CY', 'CY_SD', 'SD_SD'}
    for booking in Booking.objects.filter(service_type__in=move_type_values):
        booking.move_type = booking.service_type
        booking.service_type = ''
        booking.save(update_fields=['move_type', 'service_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_add_container_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='move_type',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('CY_CY', 'CY-CY (Yard to Yard)'), ('CY_CFS', 'CY-CFS (Yard to CFS)'), ('CY_SD', 'CY-SD (Yard to Door)'), ('CFS_CY', 'CFS-CY (CFS to Yard)'), ('CFS_CFS', 'CFS-CFS (CFS to CFS)'), ('CFS_SD', 'CFS-SD (CFS to Door)'), ('SD_CY', 'SD-CY (Door to Yard)'), ('SD_CFS', 'SD-CFS (Door to CFS)'), ('SD_SD', 'SD-SD (Door to Door)')], default='', help_text='Cargo receipt & delivery terms (sea modes only, e.g. CY-CY, CY-SD, SD-SD)', max_length=10),
        ),
        migrations.RunPython(
            migrate_service_type_to_move_type,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_TRANSIT', 'Marked In Transit'), ('ARRIVED', 'Arrived at Destination'), ('COMPLETED', 'Completed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('PARTY_ADDED', 'Party Added'), ('PARTY_REMOVED', 'Party Removed'), ('ITEM_ADDED', 'Cargo Item Added'), ('ITEM_UPDATED', 'Cargo Item Updated'), ('ITEM_REMOVED', 'Cargo Item Removed'), ('RESUBMITTED', 'Resubmitted from Rejection'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('RECONFIRMED', 'Re-confirmed after Customer Rejection'), ('CONSOLIDATED', 'Added to Consolidation'), ('UNCONSOLIDATED', 'Removed from Consolidation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('AWS', 'AWS - All Water Service'), ('IPI', 'IPI - Interior Point Intermodal'), ('MLB', 'MLB - Mini Land Bridge'), ('RIPI', 'RIPI - Reverse IPI'), ('EXPRESS', 'Express'), ('STANDARD', 'Standard'), ('DEFERRED', 'Deferred')], default='', help_text='Routing type for ocean (AWS, IPI, MLB) or service level for air (Express, Standard, Deferred)', max_length=10),
        ),
        migrations.CreateModel(
            name='Consolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consolidation_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_consolidations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidations', to='bookings.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='consolidation',
            field=models.ForeignKey(blank=True, help_text='Consolidation group this booking belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.consolidation'),
        ),
    ]
