# Generated by Django 6.0.2 on 2026-02-19 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_enforce_org_nonnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='If True, new customers in this org get this workflow automatically')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='bookings.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bookings.workflowtemplate')),
            ],
            options={
                'ordering': ['template', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REJECTED', 'Rejected'), ('PACKING', 'Packing'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('order', models.PositiveIntegerField(help_text='Display order for this status in the workflow pipeline')),
                ('is_required', models.BooleanField(default=True, help_text='Must the booking pass through this status?')),
                ('label_override', models.CharField(blank=True, help_text='Custom label for this status (leave blank for default)', max_length=100)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bookings.workflowtemplateversion')),
            ],
            options={
                'ordering': ['version', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CustomerWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_config', to='bookings.customer')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_configs', to='bookings.workflowtemplateversion')),
            ],
            options={
                'verbose_name': 'customer workflow config',
                'verbose_name_plural': 'customer workflow configs',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='workflow_version',
            field=models.ForeignKey(blank=True, help_text='Workflow version active when this booking was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.workflowtemplateversion'),
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REJECTED', 'Rejected'), ('PACKING', 'Packing'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REJECTED', 'Rejected'), ('PACKING', 'Packing'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('required_role', models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('OPS', 'Operations')], help_text='Role required to trigger this transition (blank = any)', max_length=10)),
                ('requires_reason', models.BooleanField(default=False, help_text='Does this transition require a reason/note?')),
                ('auto_skip', models.BooleanField(default=False, help_text='Auto-advance through non-required intermediate steps')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='bookings.workflowtemplateversion')),
            ],
            options={
                'ordering': ['version', 'from_status', 'to_status'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_workflow_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='unique_version_per_template'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('version', 'status'), name='unique_status_per_version'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('version', 'from_status', 'to_status'), name='unique_transition_per_version'),
        ),
    ]
