# Generated by Django 6.0.2 on 2026-02-19 04:41

from django.db import migrations


# Default workflow: all 10 statuses with all valid transitions
DEFAULT_STEPS = [
    # (status, order, is_required)
    ('DRAFT', 1, True),
    ('SUBMITTED', 2, True),
    ('CONFIRMED', 3, True),
    ('CUSTOMER_REJECTED', 4, False),
    ('REJECTED', 5, False),
    ('PACKING', 6, True),
    ('IN_TRANSIT', 7, True),
    ('ARRIVED', 8, False),
    ('COMPLETED', 9, True),
    ('CANCELLED', 10, False),
]

DEFAULT_TRANSITIONS = [
    # (from_status, to_status, requires_reason, required_role)
    # Happy path
    ('DRAFT', 'SUBMITTED', False, ''),
    ('SUBMITTED', 'CONFIRMED', False, ''),
    ('CONFIRMED', 'PACKING', False, ''),
    ('PACKING', 'IN_TRANSIT', False, ''),
    ('IN_TRANSIT', 'ARRIVED', False, ''),
    ('IN_TRANSIT', 'COMPLETED', False, ''),
    ('ARRIVED', 'COMPLETED', False, ''),
    # Rejection paths
    ('SUBMITTED', 'REJECTED', True, ''),
    ('CONFIRMED', 'REJECTED', True, ''),
    ('PACKING', 'REJECTED', True, ''),
    ('IN_TRANSIT', 'REJECTED', True, ''),
    ('ARRIVED', 'REJECTED', True, ''),
    ('REJECTED', 'DRAFT', False, ''),
    # Customer approval/rejection
    ('CONFIRMED', 'CUSTOMER_REJECTED', False, ''),
    ('CUSTOMER_REJECTED', 'CONFIRMED', False, ''),
    # Cancellation
    ('DRAFT', 'CANCELLED', False, ''),
    ('SUBMITTED', 'CANCELLED', False, ''),
    ('CONFIRMED', 'CANCELLED', True, ''),
    ('PACKING', 'CANCELLED', True, ''),
    ('CUSTOMER_REJECTED', 'CANCELLED', True, ''),
]


def create_default_workflows(apps, schema_editor):
    """Create a default workflow template for each existing organization."""
    Organization = apps.get_model('bookings', 'Organization')
    WorkflowTemplate = apps.get_model('bookings', 'WorkflowTemplate')
    WorkflowTemplateVersion = apps.get_model('bookings', 'WorkflowTemplateVersion')
    WorkflowStep = apps.get_model('bookings', 'WorkflowStep')
    WorkflowTransition = apps.get_model('bookings', 'WorkflowTransition')

    for org in Organization.objects.filter(is_active=True):
        template = WorkflowTemplate.objects.create(
            organization=org,
            name='Standard Workflow',
            description='Default booking workflow with all statuses and transitions.',
            is_default=True,
            is_active=True,
        )
        version = WorkflowTemplateVersion.objects.create(
            template=template,
            version_number=1,
            notes='Auto-generated default workflow.',
        )
        WorkflowStep.objects.bulk_create([
            WorkflowStep(
                version=version,
                status=status,
                order=order,
                is_required=is_required,
            )
            for status, order, is_required in DEFAULT_STEPS
        ])
        WorkflowTransition.objects.bulk_create([
            WorkflowTransition(
                version=version,
                from_status=from_s,
                to_status=to_s,
                requires_reason=reason,
                required_role=role,
            )
            for from_s, to_s, reason, role in DEFAULT_TRANSITIONS
        ])


def reverse_default_workflows(apps, schema_editor):
    """Remove auto-generated default workflows."""
    CustomerWorkflowConfig = apps.get_model('bookings', 'CustomerWorkflowConfig')
    WorkflowTemplate = apps.get_model('bookings', 'WorkflowTemplate')
    # Delete configs first to avoid PROTECT errors on workflow version FK
    CustomerWorkflowConfig.objects.filter(
        workflow_version__template__name='Standard Workflow'
    ).delete()
    WorkflowTemplate.objects.filter(name='Standard Workflow').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_create_workflow_models'),
    ]

    operations = [
        migrations.RunPython(
            create_default_workflows,
            reverse_default_workflows,
        ),
    ]
