# Generated by Django 6.0.2 on 2026-02-19 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_populate_default_workflows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Dict of {field_name: {visible: bool, required: bool, label: str}}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_config', to='bookings.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'field config',
                'verbose_name_plural': 'field configs',
            },
        ),
        migrations.CreateModel(
            name='OrganizationFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_consolidation', models.BooleanField(default=True, help_text='Allow grouping bookings into consolidations')),
                ('enable_import', models.BooleanField(default=True, help_text='Allow CSV/Excel/EDI import of bookings')),
                ('enable_parties', models.BooleanField(default=True, help_text='Show parties (shipper, consignee, etc.) on bookings')),
                ('enable_documents', models.BooleanField(default=True, help_text='Allow document uploads on bookings')),
                ('enable_milestones', models.BooleanField(default=True, help_text='Track shipment milestones on bookings')),
                ('enable_customer_approval', models.BooleanField(default=True, help_text='Require customer approval step before packing')),
                ('enable_carrier_integration', models.BooleanField(default=True, help_text='Enable automated carrier API integrations')),
                ('enable_fms_integration', models.BooleanField(default=True, help_text='Enable FMS (freight management system) push')),
                ('enable_templates', models.BooleanField(default=True, help_text='Allow saving and reusing booking templates')),
                ('enable_clone', models.BooleanField(default=True, help_text='Allow cloning bookings')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='bookings.organization')),
            ],
            options={
                'verbose_name': 'organization feature config',
                'verbose_name_plural': 'organization feature configs',
            },
        ),
    ]
