# Generated by Django 6.0.2 on 2026-02-19

from django.db import migrations


def create_default_feature_configs(apps, schema_editor):
    """Create a default OrganizationFeatureConfig for each active org."""
    Organization = apps.get_model('bookings', 'Organization')
    OrganizationFeatureConfig = apps.get_model('bookings', 'OrganizationFeatureConfig')

    for org in Organization.objects.filter(is_active=True):
        OrganizationFeatureConfig.objects.get_or_create(
            organization=org,
            defaults={
                'enable_consolidation': True,
                'enable_import': True,
                'enable_parties': True,
                'enable_documents': True,
                'enable_milestones': True,
                'enable_customer_approval': True,
                'enable_carrier_integration': True,
                'enable_fms_integration': True,
                'enable_templates': True,
                'enable_clone': True,
            },
        )


def reverse_default_feature_configs(apps, schema_editor):
    """Remove auto-generated default feature configs."""
    OrganizationFeatureConfig = apps.get_model('bookings', 'OrganizationFeatureConfig')
    OrganizationFeatureConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_create_feature_flag_models'),
    ]

    operations = [
        migrations.RunPython(
            create_default_feature_configs,
            reverse_default_feature_configs,
        ),
    ]
