# Generated by Django 6.0.2 on 2026-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_populate_default_feature_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Customer or external reference number (required before submission)', max_length=100),
        ),
    ]
