# Generated by Django 6.0.2 on 2026-02-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0034_optional_external_reference_in_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('SHIPPER', 'Shipper'), ('ADMIN', 'Admin'), ('OPS', 'Operations')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='required_role',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('SHIPPER', 'Shipper'), ('ADMIN', 'Admin'), ('OPS', 'Operations')], help_text='Role required to trigger this transition (blank = any)', max_length=10),
        ),
    ]
