# Generated by Django 6.0.2 on 2026-02-19 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0035_add_shipper_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='options_presented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_TRANSIT', 'Marked In Transit'), ('ARRIVED', 'Arrived at Destination'), ('COMPLETED', 'Completed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('PARTY_ADDED', 'Party Added'), ('PARTY_REMOVED', 'Party Removed'), ('ITEM_ADDED', 'Cargo Item Added'), ('ITEM_UPDATED', 'Cargo Item Updated'), ('ITEM_REMOVED', 'Cargo Item Removed'), ('RESUBMITTED', 'Resubmitted from Rejection'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('RECONFIRMED', 'Re-confirmed after Customer Rejection'), ('OPTIONS_PRESENTED', 'Carrier Options Presented'), ('OPTION_SELECTED', 'Carrier Option Selected'), ('CONSOLIDATED', 'Added to Consolidation'), ('UNCONSOLIDATED', 'Removed from Consolidation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('OPTIONS_PRESENTED', 'Options Presented'), ('CONFIRMED', 'Confirmed'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REJECTED', 'Rejected'), ('PACKING', 'Packing'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_SUBMITTED', 'Booking Submitted'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_IN_TRANSIT', 'Booking In Transit'), ('BOOKING_ARRIVED', 'Booking Arrived'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_RESUBMITTED', 'Booking Resubmitted'), ('BOOKING_CUSTOMER_APPROVED', 'Booking Customer Approved'), ('BOOKING_CUSTOMER_REJECTED', 'Booking Customer Rejected'), ('BOOKING_OPTIONS_PRESENTED', 'Carrier Options Presented'), ('BOOKING_OPTION_SELECTED', 'Carrier Option Selected'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('OPTIONS_PRESENTED', 'Options Presented'), ('CONFIRMED', 'Confirmed'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REJECTED', 'Rejected'), ('PACKING', 'Packing'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='from_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('OPTIONS_PRESENTED', 'Options Presented'), ('CONFIRMED', 'Confirmed'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REJECTED', 'Rejected'), ('PACKING', 'Packing'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('OPTIONS_PRESENTED', 'Options Presented'), ('CONFIRMED', 'Confirmed'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REJECTED', 'Rejected'), ('PACKING', 'Packing'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='CarrierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, help_text='Carrier name (auto-filled from carrier FK if set)', max_length=200)),
                ('vessel_name', models.CharField(blank=True, max_length=200)),
                ('voyage_number', models.CharField(blank=True, max_length=50)),
                ('etd', models.DateField(blank=True, null=True, verbose_name='ETD')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('transit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Quoted cost for this option', max_digits=12, null=True)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_options', to='bookings.booking')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.carrier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_option',
            field=models.ForeignKey(blank=True, help_text='Customer-selected carrier option (from options workflow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.carrieroption'),
        ),
    ]
