# Generated by Django 6.0.2 on 2026-02-19 13:52

from django.db import migrations


def add_options_presented(apps, schema_editor):
    """Add OPTIONS_PRESENTED step and transitions to all existing default workflows."""
    WorkflowTemplate = apps.get_model('bookings', 'WorkflowTemplate')
    WorkflowStep = apps.get_model('bookings', 'WorkflowStep')
    WorkflowTransition = apps.get_model('bookings', 'WorkflowTransition')

    for template in WorkflowTemplate.objects.filter(name='Standard Workflow'):
        for version in template.versions.all():
            # Add OPTIONS_PRESENTED step (between SUBMITTED=2 and CONFIRMED=3)
            if not version.steps.filter(status='OPTIONS_PRESENTED').exists():
                # Shift existing steps with order >= 3 to make room
                for step in version.steps.filter(order__gte=3).order_by('-order'):
                    step.order += 1
                    step.save()

                WorkflowStep.objects.create(
                    version=version,
                    status='OPTIONS_PRESENTED',
                    order=3,
                    is_required=False,  # Optional step — can skip directly to confirm
                )

            # Add transitions for OPTIONS_PRESENTED
            new_transitions = [
                ('SUBMITTED', 'OPTIONS_PRESENTED', False, ''),
                ('OPTIONS_PRESENTED', 'CONFIRMED', False, ''),
                ('OPTIONS_PRESENTED', 'REJECTED', True, ''),
                ('OPTIONS_PRESENTED', 'CANCELLED', False, ''),
            ]
            for from_s, to_s, reason, role in new_transitions:
                WorkflowTransition.objects.get_or_create(
                    version=version,
                    from_status=from_s,
                    to_status=to_s,
                    defaults={
                        'requires_reason': reason,
                        'required_role': role,
                    },
                )


def reverse_options_presented(apps, schema_editor):
    """Remove OPTIONS_PRESENTED steps and transitions from default workflows."""
    WorkflowStep = apps.get_model('bookings', 'WorkflowStep')
    WorkflowTransition = apps.get_model('bookings', 'WorkflowTransition')

    WorkflowStep.objects.filter(status='OPTIONS_PRESENTED').delete()
    WorkflowTransition.objects.filter(from_status='OPTIONS_PRESENTED').delete()
    WorkflowTransition.objects.filter(to_status='OPTIONS_PRESENTED').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_carrier_options_workflow'),
    ]

    operations = [
        migrations.RunPython(
            add_options_presented,
            reverse_options_presented,
        ),
    ]
