# Generated by Django 6.0.2 on 2026-02-19 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0037_add_options_presented_to_default_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('RAIL', 'Rail'), ('ROAD', 'Road')], default='SEA', max_length=10)),
                ('rate_amount', models.DecimalField(decimal_places=2, help_text='Rate amount per unit (container, kg, CBM)', max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CNY', 'CNY'), ('JPY', 'JPY')], default='USD', max_length=3)),
                ('rate_basis', models.CharField(choices=[('PER_CONTAINER', 'Per Container'), ('PER_KG', 'Per Kilogram'), ('PER_CBM', 'Per Cubic Meter'), ('FLAT', 'Flat Rate')], default='PER_CONTAINER', help_text='How the rate is measured', max_length=20)),
                ('transit_days', models.PositiveIntegerField(blank=True, help_text='Expected transit time in days', null=True)),
                ('valid_from', models.DateField(help_text='Rate effective from date')),
                ('valid_to', models.DateField(help_text='Rate effective until date')),
                ('notes', models.TextField(blank=True, help_text='Additional terms or conditions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_sheets', to='bookings.carrier')),
                ('container_type', models.ForeignKey(blank=True, help_text='Applicable container type (for FCL rates)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.containertype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_sheets_destination', to='bookings.port')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_sheets', to='bookings.organization')),
                ('origin_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_sheets_origin', to='bookings.port')),
            ],
            options={
                'ordering': ['-valid_from', 'carrier__name'],
                'indexes': [models.Index(fields=['origin_port', 'destination_port', 'carrier'], name='bookings_ra_origin__14cfa3_idx'), models.Index(fields=['valid_from', 'valid_to'], name='bookings_ra_valid_f_02f41e_idx')],
            },
        ),
    ]
