# Generated by Django 6.0.2 on 2026-02-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0038_create_rate_sheet_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtransition',
            name='allowed_company_types',
            field=models.JSONField(blank=True, default=list, help_text='Company types that can trigger this transition. Empty list = any type (staff or customer). Example: ["FORWARDER_ORIGIN", "SHIPPER"]'),
        ),
    ]
