# Generated by Django 6.0.2 on 2026-02-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0039_workflowtransition_allowed_company_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_customers',
            field=models.ManyToManyField(blank=True, help_text='Additional companies this user represents beyond primary', related_name='additional_user_profiles', to='bookings.customer'),
        ),
    ]
