# Generated by Django 6.0.2 on 2026-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0040_userprofile_additional_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_document_review',
            field=models.BooleanField(default=True, help_text='Enable AI-powered document review for PDFs'),
        ),
    ]
