# Generated by Django 6.0.2 on 2026-02-21 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0041_add_enable_document_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='freight_terms',
            field=models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect'), ('THIRD_PARTY', 'Third Party')], help_text='Freight payment terms for Bill of Lading', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_originals',
            field=models.PositiveIntegerField(default=3, help_text='Number of original BL copies'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_auto_quoting',
            field=models.BooleanField(default=True, help_text='Show matching rates when creating bookings'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_booking_comments',
            field=models.BooleanField(default=True, help_text='Enable threaded comments on bookings'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_document_to_booking',
            field=models.BooleanField(default=True, help_text='Create bookings from uploaded PDF documents'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_email_to_booking',
            field=models.BooleanField(default=False, help_text='Create bookings from inbound emails'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_hbl_generation',
            field=models.BooleanField(default=True, help_text='Generate draft House Bill of Lading PDFs'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_phone_notifications',
            field=models.BooleanField(default=False, help_text='Enable WhatsApp/SMS notifications via Twilio'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_sanctions_screening',
            field=models.BooleanField(default=True, help_text='Screen parties against OFAC/EU/UN sanctions lists'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_scheduled_reports',
            field=models.BooleanField(default=True, help_text='Allow scheduling recurring email reports'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_sla_tracking',
            field=models.BooleanField(default=True, help_text='Track SLA timers and auto-escalate breaches'),
        ),
        migrations.AddField(
            model_name='organizationfeatureconfig',
            name='enable_tracking',
            field=models.BooleanField(default=False, help_text='Real-time vessel/container tracking via external API'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_notifications',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications for critical events'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_notifications',
            field=models.BooleanField(default=False, help_text='Receive WhatsApp notifications for critical events'),
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='bookings.booking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('WEEKLY_SUMMARY', 'Weekly Summary'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('CARRIER_PERFORMANCE', 'Carrier Performance'), ('VOLUME_BY_CUSTOMER', 'Volume by Customer')], max_length=30)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (for weekly)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-28 (for monthly)', null=True)),
                ('hour', models.IntegerField(default=7, help_text='Hour to send (0-23)')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='bookings.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('max_hours', models.PositiveIntegerField(help_text='Maximum hours allowed in this status')),
                ('warning_pct', models.PositiveIntegerField(default=75, help_text='Percentage of max_hours to trigger warning')),
                ('escalation_email', models.EmailField(blank=True, help_text='Email to notify on breach', max_length=254)),
                ('escalation_action', models.CharField(choices=[('NOTIFY', 'Send notification'), ('FLAG', 'Flag in dashboard'), ('BOTH', 'Notify and flag')], default='BOTH', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_configs', to='bookings.organization')),
            ],
            options={
                'ordering': ['status'],
                'unique_together': {('organization', 'status')},
            },
        ),
        migrations.CreateModel(
            name='SLABreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('entered_at', models.DateTimeField(help_text='When booking entered this status')),
                ('breached_at', models.DateTimeField(help_text='When the SLA was breached')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_breaches', to='bookings.booking')),
                ('sla_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='bookings.slaconfig')),
            ],
            options={
                'ordering': ['-breached_at'],
            },
        ),
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_knots', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vessel_name'], name='bookings_ve_vessel__606d9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments visible only to staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookings.booking')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_2bc0a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_checked', models.CharField(help_text='OFAC, EU, or UN', max_length=20)),
                ('status', models.CharField(choices=[('CLEAR', 'Clear'), ('POTENTIAL_MATCH', 'Potential Match'), ('BLOCKED', 'Blocked'), ('REVIEWED_OK', 'Reviewed - Cleared'), ('REVIEWED_BLOCKED', 'Reviewed - Blocked')], max_length=20)),
                ('match_score', models.FloatField(default=0.0, help_text='0.0-1.0 similarity')),
                ('match_details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='bookings.party')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['party', '-checked_at'], name='bookings_sc_party_i_7b7a81_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('vessel_name', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('API', 'External API'), ('MANUAL', 'Manual Entry')], default='API', max_length=10)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='bookings.booking')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['booking', '-occurred_at'], name='bookings_tr_booking_56af72_idx')],
            },
        ),
    ]
