# Generated by Django 6.0.2 on 2026-02-09 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0010_add_fms_integration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter_type', models.CharField(choices=[('webhook', 'Generic Webhook (JSON POST)'), ('cargowise', 'CargoWise eAdaptor'), ('dcsa', 'DCSA Booking API'), ('file_drop', 'File Drop (SFTP/EDI)')], max_length=30)),
                ('api_endpoint', models.URLField(help_text='FMS API endpoint URL')),
                ('auth_type', models.CharField(choices=[('token', 'API Token / Bearer'), ('oauth2', 'OAuth 2.0 Client Credentials'), ('basic', 'Basic Auth'), ('certificate', 'Client Certificate')], default='token', max_length=20)),
                ('api_key', models.CharField(blank=True, help_text='API key or OAuth client ID', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API secret or OAuth client secret', max_length=500)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Additional adapter-specific settings (JSON)')),
                ('auto_push_on_confirm', models.BooleanField(default=True, help_text='Automatically push to FMS when booking is confirmed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_config', to='bookings.customer')),
            ],
            options={
                'verbose_name': 'FMS integration config',
                'verbose_name_plural': 'FMS integration configs',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('PUSH', 'Push to FMS'), ('PUSH_SUCCESS', 'Push Successful'), ('PUSH_FAILED', 'Push Failed'), ('CALLBACK', 'Callback Received'), ('UPDATE', 'Milestone Update'), ('CANCEL', 'Cancellation Sent'), ('RETRY', 'Manual Retry')], max_length=20)),
                ('adapter_type', models.CharField(blank=True, max_length=30)),
                ('request_payload', models.JSONField(blank=True, help_text='Outbound payload sent to FMS', null=True)),
                ('response_payload', models.JSONField(blank=True, help_text='Response received from FMS', null=True)),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP status code of FMS response', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='bookings.booking')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.integrationconfig')),
            ],
            options={
                'verbose_name': 'FMS integration log',
                'verbose_name_plural': 'FMS integration logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
