# Generated by Django 6.0.2 on 2026-02-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_code', models.CharField(help_text='SCAC code for ocean (e.g. MAEU), IATA code for air (e.g. LH)', max_length=20, unique=True)),
                ('carrier_name', models.CharField(help_text='Display name e.g. Maersk', max_length=100)),
                ('carrier_type', models.CharField(choices=[('ocean', 'Ocean Carrier'), ('air', 'Air Carrier'), ('rail', 'Rail Carrier'), ('trucking', 'Trucking Carrier')], max_length=20)),
                ('adapter_type', models.CharField(choices=[('carrier_webhook', 'Generic Webhook (JSON POST)'), ('dcsa', 'DCSA Booking API v2'), ('one_record', 'IATA ONE Record')], max_length=30)),
                ('api_endpoint', models.URLField(help_text='Carrier API base URL')),
                ('auth_type', models.CharField(choices=[('token', 'API Token / Bearer'), ('oauth2', 'OAuth 2.0 Client Credentials'), ('basic', 'Basic Auth')], default='token', max_length=20)),
                ('api_key', models.CharField(blank=True, help_text='API key or OAuth client ID', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API secret or OAuth client secret', max_length=500)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Carrier-specific settings (JSON)')),
                ('supports_async_callback', models.BooleanField(default=True, help_text='Carrier confirms via async callback (vs synchronous response)')),
                ('auto_chain_to_fms', models.BooleanField(default=True, help_text='Automatically push to customer FMS after carrier confirms')),
                ('callback_secret', models.CharField(blank=True, help_text='Shared secret for validating carrier callback signatures', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'carrier config',
                'verbose_name_plural': 'carrier configs',
                'ordering': ['carrier_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='integrationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'integration log', 'verbose_name_plural': 'integration logs'},
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='event',
            field=models.CharField(choices=[('PUSH', 'Push to FMS'), ('PUSH_SUCCESS', 'Push Successful'), ('PUSH_FAILED', 'Push Failed'), ('CALLBACK', 'Callback Received'), ('UPDATE', 'Milestone Update'), ('CANCEL', 'Cancellation Sent'), ('RETRY', 'Manual Retry'), ('CARRIER_SUBMIT', 'Carrier Booking Submitted'), ('CARRIER_SUCCESS', 'Carrier Submission Accepted'), ('CARRIER_FAILED', 'Carrier Submission Failed'), ('CARRIER_CALLBACK', 'Carrier Callback Received'), ('CARRIER_CONFIRMED', 'Carrier Booking Confirmed'), ('CARRIER_REJECTED', 'Carrier Booking Rejected'), ('CARRIER_CANCEL', 'Carrier Cancellation Sent')], max_length=20),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='carrier_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.carrierconfig'),
        ),
    ]
