# Generated by Django 6.0.2 on 2026-02-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_webhooksubscription_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='max_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='success',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
