# Generated by Django 6.0.2 on 2026-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_webhookdelivery_retry_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierconfig',
            name='adapter_type',
            field=models.CharField(choices=[('carrier_webhook', 'Generic Webhook (JSON POST)'), ('dcsa', 'DCSA Booking API v2'), ('one_record', 'IATA ONE Record'), ('maersk', 'Maersk API')], max_length=30),
        ),
    ]
